package com.jzc.domain;

public class BusinessType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businesstype.id
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businesstype.name
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businesstype.id
     *
     * @return the value of businesstype.id
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businesstype.id
     *
     * @param id the value for businesstype.id
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businesstype.name
     *
     * @return the value of businesstype.name
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businesstype.name
     *
     * @param name the value for businesstype.name
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }
}