package com.jzc.domain;

public class CompanyInfoWithBLOBs extends CompanyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companyinfo.introduction
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companyinfo.philosophy
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private String philosophy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companyinfo.history
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private String history;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companyinfo.introduction
     *
     * @return the value of companyinfo.introduction
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companyinfo.introduction
     *
     * @param introduction the value for companyinfo.introduction
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companyinfo.philosophy
     *
     * @return the value of companyinfo.philosophy
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public String getPhilosophy() {
        return philosophy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companyinfo.philosophy
     *
     * @param philosophy the value for companyinfo.philosophy
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setPhilosophy(String philosophy) {
        this.philosophy = philosophy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companyinfo.history
     *
     * @return the value of companyinfo.history
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public String getHistory() {
        return history;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companyinfo.history
     *
     * @param history the value for companyinfo.history
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setHistory(String history) {
        this.history = history;
    }
}