package com.jzc.domain;

import java.util.Date;


public class CompanyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companyinfo.id
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companyinfo.name
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companyinfo.founder
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private String founder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column companyinfo.founddate
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private Date founddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companyinfo.id
     *
     * @return the value of companyinfo.id
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companyinfo.id
     *
     * @param id the value for companyinfo.id
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companyinfo.name
     *
     * @return the value of companyinfo.name
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companyinfo.name
     *
     * @param name the value for companyinfo.name
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companyinfo.founder
     *
     * @return the value of companyinfo.founder
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public String getFounder() {
        return founder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companyinfo.founder
     *
     * @param founder the value for companyinfo.founder
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setFounder(String founder) {
        this.founder = founder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column companyinfo.founddate
     *
     * @return the value of companyinfo.founddate
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public Date getFounddate() {
        return founddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column companyinfo.founddate
     *
     * @param founddate the value for companyinfo.founddate
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setFounddate(Date founddate) {
        this.founddate = founddate;
    }
}