package com.jzc.domain;

import java.util.Date;

public class New {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.publishtime
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private Date publishtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.author
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.clicknum
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private Integer clicknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.tid
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private Integer tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.publishtime
     *
     * @return the value of news.publishtime
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public Date getPublishtime() {
        return publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.publishtime
     *
     * @param publishtime the value for news.publishtime
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setPublishtime(Date publishtime) {
        this.publishtime = publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.author
     *
     * @return the value of news.author
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.author
     *
     * @param author the value for news.author
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.clicknum
     *
     * @return the value of news.clicknum
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public Integer getClicknum() {
        return clicknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.clicknum
     *
     * @param clicknum the value for news.clicknum
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setClicknum(Integer clicknum) {
        this.clicknum = clicknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.tid
     *
     * @return the value of news.tid
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.tid
     *
     * @param tid the value for news.tid
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }
}