package com.jzc.domain;

public class NewType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newstype.id
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newstype.type
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newstype.id
     *
     * @return the value of newstype.id
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newstype.id
     *
     * @param id the value for newstype.id
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newstype.type
     *
     * @return the value of newstype.type
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newstype.type
     *
     * @param type the value for newstype.type
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }
}