package com.jzc.domain;

public class Technology {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology.id
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology.name
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology.tid
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private Integer tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology.id
     *
     * @return the value of technology.id
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology.id
     *
     * @param id the value for technology.id
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology.name
     *
     * @return the value of technology.name
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology.name
     *
     * @param name the value for technology.name
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology.tid
     *
     * @return the value of technology.tid
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology.tid
     *
     * @param tid the value for technology.tid
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }
}