package com.jzc.domain;

public class TechnologyWithBLOBs extends Technology {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology.introduction
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology.picture
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology.video
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    private String video;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology.introduction
     *
     * @return the value of technology.introduction
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology.introduction
     *
     * @param introduction the value for technology.introduction
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology.picture
     *
     * @return the value of technology.picture
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology.picture
     *
     * @param picture the value for technology.picture
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology.video
     *
     * @return the value of technology.video
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology.video
     *
     * @param video the value for technology.video
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    public void setVideo(String video) {
        this.video = video;
    }
}