package com.jzc.dao;

import com.jzc.domain.BusinessType;

public interface BusinessTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table businesstype
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table businesstype
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int insert(BusinessType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table businesstype
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int insertSelective(BusinessType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table businesstype
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    BusinessType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table businesstype
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int updateByPrimaryKeySelective(BusinessType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table businesstype
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int updateByPrimaryKey(BusinessType record);
}