package com.jzc.dao;

import java.util.List;

import com.jzc.domain.Business;
import com.jzc.domain.BusinessWithBLOBs;

public interface BusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int insert(BusinessWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int insertSelective(BusinessWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    BusinessWithBLOBs selectByPrimaryKey(Integer id);
    
    List<BusinessWithBLOBs> selectBusList(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int updateByPrimaryKeySelective(BusinessWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(BusinessWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int updateByPrimaryKey(Business record);
}