package com.jzc.dao;

import com.jzc.domain.NewType;

public interface NewTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newstype
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newstype
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int insert(NewType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newstype
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int insertSelective(NewType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newstype
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    NewType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newstype
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int updateByPrimaryKeySelective(NewType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newstype
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int updateByPrimaryKey(NewType record);
}