package com.jzc.dao;

import java.util.List;

import com.jzc.domain.Technology;
import com.jzc.domain.TechnologyWithBLOBs;

public interface TechnologyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int insert(TechnologyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int insertSelective(TechnologyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    TechnologyWithBLOBs selectByPrimaryKey(Integer id);

    List<TechnologyWithBLOBs> selectTechList(Integer tid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int updateByPrimaryKeySelective(TechnologyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(TechnologyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int updateByPrimaryKey(Technology record);
}