package com.jzc.dao;

import com.jzc.domain.TechType;

public interface TechTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table techtype
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table techtype
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int insert(TechType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table techtype
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int insertSelective(TechType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table techtype
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    TechType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table techtype
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int updateByPrimaryKeySelective(TechType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table techtype
     *
     * @mbggenerated Thu Jun 30 15:30:09 CST 2016
     */
    int updateByPrimaryKey(TechType record);
}